[package]
name = "dioxus-stuff"
version = "0.1.0"
authors = ["jaankaup"]
edition = "2021"
resolver = "2"
# default-run = ""
publish = false

[dependencies]
workspace.dioxus = true
workspace.dioxus-desktop = true
workspace.dioxus-html = true
